In [2]:
import numpy as np

# 矩阵 6 * 5
x = np.matrix([
    [1.00, 96.79, 2.00, 1.00, 2.00],
    [1.00, 110.39, 3.00, 1.00, 0.00],
    [1.00, 70.25, 1.00, 0.00, 2.00],
    [1.00, 99.96, 2.00, 1.00, 1.00],
    [1.00, 118.15, 3.00, 1.00, 0.00],
    [1.00, 115.08, 3.00, 1.00, 2.00]
])

# 列向量 6 * 1
y = np.matrix([
    [287], [343], [199], [298], [340], [350],
])

In [6]:
x_t = x.T
A = np.dot(x_t, x)
A_inv = np.linalg.inv(A) # 求逆
B = np.dot(x_t, y)
w = (x.T * x).I * x.T * y
w

matrix([[124.55946459],
        [  0.31882858],
        [ 48.25692773],
        [ 37.22249353],
        [  1.89295003]])

In [7]:
cost = (y - np.dot(x, w)).T.dot(y - np.dot(x, w)) / ( 2 * x.shape[0])
cost

matrix([[8.23445195]])

In [8]:
test = [[1, 112, 3, 1, 0],
        [1, 110, 3, 1, 1]
        ]

np.dot(test, w)

matrix([[342.26154206],
        [343.51683493]])