In [3]:
import torch

a = torch.tensor([
    [1, 2, 3]
])
b = torch.tensor([
    [4, 5, 6]
])
c = torch.mul(a, b)
print(c)

torch.dot(a[0], b[0])

tensor([[ 4, 10, 18]])


tensor(32)

In [8]:
import torch

a = torch.tensor([[1, 2, 3]])
a.unsqueeze(2)

tensor([[[1],
         [2],
         [3]]])

In [18]:
import torch

a = torch.tensor(
    [2.5, 1.2, 1]
)

torch.sigmoid(a)

tensor([0.9241, 0.7685, 0.7311])

In [24]:
def corpus_reader(file_path):
    with open(file_path, 'r', encoding='utf-8') as f:
        for line in f:
            yield line.strip()


result = corpus_reader('data/1.txt')
for line in result:
    print(line)

人工智能（Artificial Intelligence，简称 ai）是一门研究、开发用于模拟、延伸和扩展人类智能的技术科学。
yield
一、主要特点
yield
学习能力：人工智能系统可以通过大量的数据进行学习，不断改进自己的性能。例如，机器学习算法可以从数据中自动发现模式和规律，从而对新的数据进行预测和分类。
yield
适应性：能够适应不同的环境和任务。随着新数据的输入和任务的变化，人工智能系统可以调整自己的参数和策略，以更好地完成任务。
yield
自动化：可以自动执行复杂的任务，减少人类的工作量和错误率。例如，自动化的图像识别系统可以快速准确地识别大量的图像，而无需人工干预。
yield
智能决策：基于数据和算法进行智能决策。在复杂的情况下，人工智能系统可以分析各种因素，权衡利弊，做出最优的决策。
yield


In [1]:
import torch

a = torch.tensor([
    [1, 2],
    [3, 4]
])

b = torch.tensor([
    [5, 6],
    [7, 8]
])

torch.mul(a, b)

In [30]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()
corpus = [
    'This is the first document.',
    'This document is the second document.',
    'And this is the third one.',
    'Is this the first document?'
]
X = vectorizer.fit_transform(corpus)
vectorizer.vocabulary_, X.toarray()

({'this': 8,
  'is': 3,
  'the': 6,
  'first': 2,
  'document': 1,
  'second': 5,
  'and': 0,
  'third': 7,
  'one': 4},
 array([[0, 1, 1, 1, 0, 0, 1, 0, 1],
        [0, 2, 0, 1, 0, 1, 1, 0, 1],
        [1, 0, 0, 1, 1, 0, 1, 1, 1],
        [0, 1, 1, 1, 0, 0, 1, 0, 1]]))

In [35]:
import re
import numpy as np

corpus = [
    'This is the first document.',
    'This document is the second document.',
    'And this is the third one.',
    'Is this the first document?'
]

word_freq: dict[str, int] = {}
for line in corpus:
    new_line = re.sub(r'[,.?]', '', line)
    for word in new_line.lower().split():
        word_freq[word] = word_freq.get(word, 0) + 1

sorted_word_freq = {k: word_freq[k] for k in sorted(word_freq.keys())}
word2idx = {word: idx for idx, word in enumerate(sorted_word_freq.keys())}
idx2word = {idx: word for idx, word in enumerate(sorted_word_freq.keys())}

matrix = np.zeros((len(corpus), len(word2idx)), dtype=np.int32)
for i, line in enumerate(corpus):
    new_line = re.sub(r'[,.?]', '', line)
    for word in new_line.lower().split():
        matrix[i, word2idx[word]] += 1

print(matrix)

[[0 1 1 1 0 0 1 0 1]
 [0 2 0 1 0 1 1 0 1]
 [1 0 0 1 1 0 1 1 1]
 [0 1 1 1 0 0 1 0 1]]


In [67]:
from sklearn.feature_extraction.text import TfidfVectorizer
corpus = [
    'this is a sample this sample',
    'another sample document'
]

vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(corpus)

vectorizer.get_feature_names_out(), X.toarray()

(array(['another', 'document', 'is', 'sample', 'this'], dtype=object),
 array([[0.        , 0.        , 0.37729199, 0.53689271, 0.75458397],
        [0.6316672 , 0.6316672 , 0.        , 0.44943642, 0.        ]]))

In [62]:
corpus = [
    'this is a sample this sample',
    'another sample document'
]

stop_words = {'a'}
word_freq: dict[str, int] = {}
term_freq: list[dict[str, int]] = [{}, {}]
for i, line in enumerate(corpus):
    new_line = re.sub(r'[,.?]', '', line)
    for word in new_line.lower().split():
        if word in stop_words:
            continue
        word_freq[word] = word_freq.get(word, 0) + 1
        term_freq[i][word] = term_freq[i].get(word, 0) + 1

sorted_term_freq = {k: word_freq[k] for k in sorted(word_freq.keys())}
word2idx = {word: idx for idx, word in enumerate(sorted_term_freq.keys())}
idx2word = {idx: word for idx, word in enumerate(sorted_term_freq.keys())}

matrix = np.zeros((len(corpus), len(word2idx)), dtype=np.float32)
for i, line in enumerate(corpus):
    new_line = re.sub(r'[,.?]', '', line)
    for word in new_line.lower().split():
        if word in stop_words:
            continue

        tf = term_freq[i][word] / sum(term_freq[i].values())
        idf = 1 + np.log((len(term_freq) + 1) /
                         (1 + sum(1 for freq in term_freq if word in freq)))
        matrix[i, word2idx[word]] = tf * idf

sorted_term_freq.keys(), matrix / np.linalg.norm(matrix, axis=1, keepdims=True)

(dict_keys(['another', 'document', 'is', 'sample', 'this']),
 array([[0.        , 0.        , 0.37729198, 0.5368927 , 0.75458395],
        [0.6316672 , 0.6316672 , 0.        , 0.44943643, 0.        ]],
       dtype=float32))