In [3]:
import torch

a = torch.tensor([
    [1, 2, 3]
])
b = torch.tensor([
    [4, 5, 6]
])
c = torch.mul(a, b)
print(c)

torch.dot(a[0], b[0])

tensor([[ 4, 10, 18]])


tensor(32)

In [8]:
import torch

a = torch.tensor([[1, 2, 3]])
a.unsqueeze(2)

tensor([[[1],
         [2],
         [3]]])

In [18]:
import torch

a = torch.tensor(
    [2.5, 1.2, 1]
)

torch.sigmoid(a)

tensor([0.9241, 0.7685, 0.7311])

In [24]:
def corpus_reader(file_path):
    with open(file_path, 'r', encoding='utf-8') as f:
        for line in f:
            yield line.strip()


result = corpus_reader('data/1.txt')
for line in result:
    print(line)

人工智能（Artificial Intelligence，简称 ai）是一门研究、开发用于模拟、延伸和扩展人类智能的技术科学。
yield
一、主要特点
yield
学习能力：人工智能系统可以通过大量的数据进行学习，不断改进自己的性能。例如，机器学习算法可以从数据中自动发现模式和规律，从而对新的数据进行预测和分类。
yield
适应性：能够适应不同的环境和任务。随着新数据的输入和任务的变化，人工智能系统可以调整自己的参数和策略，以更好地完成任务。
yield
自动化：可以自动执行复杂的任务，减少人类的工作量和错误率。例如，自动化的图像识别系统可以快速准确地识别大量的图像，而无需人工干预。
yield
智能决策：基于数据和算法进行智能决策。在复杂的情况下，人工智能系统可以分析各种因素，权衡利弊，做出最优的决策。
yield


In [1]:
import torch

a = torch.tensor([
    [1, 2],
    [3, 4]
])

b = torch.tensor([
    [5, 6],
    [7, 8]
])

torch.mul(a, b)