In [4]:
import torch


def f(x):
    """ 计算 x^2 - 4x - 5 的值 """
    return x**2 - 4*x - 5


def df(x):
    """ 计算 f(x) 的导数 """
    return 2 * x - 4


x = torch.tensor([5.0], requires_grad=True)
y = f(x)
y.backward()

In [7]:
x.data, x.grad, df(x.data)

(tensor([5.]), tensor([6.]), tensor([6.]))

In [9]:
x.grad.zero_()
x.grad

y = f(x)
y.backward()

In [10]:
x.data, x.grad, df(x.data)

(tensor([5.]), tensor([6.]), tensor([6.]))

In [11]:
y = f(x)
y.backward()

In [12]:
x.data, x.grad, df(x.data)

(tensor([5.]), tensor([12.]), tensor([6.]))

In [14]:
def f(x):
    return x ** 2 - 4 * x - 5


x = torch.tensor([0.0], requires_grad=True)
iterations = 1000
alpha = 0.01

for i in range(iterations):
    y = f(x)
    y.backward()
    x.data.sub_(alpha * x.grad)
    x.grad.zero_()

x.data, f(x.data), df(x.data)

(tensor([2.0000]), tensor([-9.]), tensor([-5.7220e-06]))