In [4]:
import torch

In [34]:
a = torch.tensor([1, 2, 3, 4, 5])

In [37]:
b = torch.Tensor(2, 3)

In [40]:
c = torch.tensor([
    [1, 2, 3],
    [4, 5, 6]
])

In [46]:
d = torch.rand(3, 3)

In [59]:
e = torch.Tensor(d)
e

tensor([[0.7340, 0.5142, 0.9433],
        [0.6730, 0.6687, 0.6375],
        [0.1799, 0.8724, 0.1062]])

In [61]:
array = [1, 2, 3, 4, 5]
long_tensor = torch.tensor(array, )
float_tensor = torch.Tensor(array)
long_tensor.type(), float_tensor.type()

('torch.LongTensor', 'torch.FloatTensor')

In [62]:
long_tensor

tensor([1, 2, 3, 4, 5])

In [68]:
long_tensor.shape, long_tensor.size()

(torch.Size([5]), torch.Size([5]))

In [72]:
torch.ones(3, 3, dtype=torch.int32)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)

In [77]:
torch.zeros(3, 3).type()

'torch.FloatTensor'

In [80]:
torch.randn(3, 3).mean(), torch.randn(3, 3).mean(), torch.randn(3, 3).mean(),

(tensor(0.0538), tensor(0.0644), tensor(-0.0495))

In [88]:
torch.linspace(0, 10, steps=6, layout=torch.strided)

tensor([ 0.,  2.,  4.,  6.,  8., 10.])