In [1]:
import torch as t #导入torch库

In [2]:
#创建一个2乘3的张量a
a = t.Tensor([[1, 2, 3], [4, 5, 6]])

In [3]:
#打印a点size，得到它的形状
print(a.size())

torch.Size([2, 3])


In [4]:
#创建值为1的张量
z1 = t.ones(2, 3)
print(z1)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [5]:
#创建值为0的张量
z2 = t.zeros(2, 3)
print(z2)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [6]:
#创建标准正太分布的随机数
z3 = t.randn(2, 3)
print(z3)

tensor([[-0.0480,  0.7712,  1.0522],
        [-1.4677,  0.6182,  0.6102]])


In [7]:
#创建一个范围内的均匀数据
z4 = t.linspace(1, 10, 5)
print(z4)

tensor([ 1.0000,  3.2500,  5.5000,  7.7500, 10.0000])
