In [2]:
import torch

a = torch.tensor([
    [1, 2, 3],
    [4, 5, 6]
])

a.T

tensor([[1, 4],
        [2, 5],
        [3, 6]])

In [ ]:
class Seq2Seq(nn.Module):
    def __init__(self, encoder, decoder, device):
        super(Seq2Seq, self).__init__()
        self.encoder = encoder
        self.decoder = decoder
        self.device = device

    def forward(self, src, trg, teacher_forcing_ratio=0.5):
        # src: [src_len, batch_size]
        # trg: [trg_len, batch_size]
        batch_size = trg.shape[1]
        trg_len = trg.shape[0]
        trg_vocab_size = self.decoder.fc_out.out_features

        # 初始化输出张量
        outputs = torch.zeros(trg_len, batch_size,
                              trg_vocab_size).to(self.device)

        # 编码器输出
        encoder_outputs, hidden = self.encoder(src)

        # 初始化解码器的输入为 <sos>
        input = trg[0, :]

        # 初始化解码器的细胞状态（这里假设为零）
        cell = torch.zeros_like(hidden).to(self.device)

        for t in range(1, trg_len):
            # 解码器输出
            output, hidden, cell = self.decoder(input, hidden, cell)
            outputs[t] = output

            # 决定是否使用教师强制
            teacher_force = torch.rand(1).item() < teacher_forcing_ratio
            top1 = output.argmax(1)

            input = trg[t] if teacher_force else top1

        return outputs

In [4]:
import torch
import torch.nn as nn

# 创建一个张量
tensor = torch.empty(3, 4)

# 使用 nn.init.uniform_ 初始化张量
nn.init.uniform_(tensor, a=0, b=1)

print(tensor)

tensor([[0.1858, 0.5294, 0.5080, 0.3781],
        [0.9861, 0.0089, 0.3523, 0.9723],
        [0.2612, 0.4881, 0.7245, 0.9195]])


In [20]:
import torch
import torch.nn as nn
hid_dim = 3
a = torch.rand(hid_dim)
v = nn.Parameter(a)  # 可学习的参数向
b = a.clone().detach().requires_grad_(True)  # 非参数向量

v, b

(Parameter containing:
 tensor([0.7375, 0.5543, 0.5921], requires_grad=True),
 tensor([0.7375, 0.5543, 0.5921], requires_grad=True))

In [40]:
import torch
if torch.rand(1) < 1:
    print('ok')

ok


In [2]:
import jieba
import spacy

In [3]:
import pandas as pd
df = pd.DataFrame({
    'Name': ['Alice', 'Bob'],
    'Age': [25, 30]
})

rows_to_add = []
for i in range(3):
    # new_row = {'Name': f'Person{i}', 'Age': 20 + i}
    new_row = [f'Person{i}', 20 + i]
    rows_to_add.append(new_row)
new_df = pd.DataFrame(rows_to_add, columns=['Name', 'Age'])
new_df

Name  Age
0  Person0   20
1  Person1   21
2  Person2   22

In [10]:
from tqdm import tqdm
for i in (range(len(tqdm([1, 2, 3])))):
    pass

  0%|          | 0/3 [00:00<?, ?it/s]


In [2]:
from typing import Any


class Test():
    def __init__(self) -> None:
        self.word_2_index = {
            'hi': 0
        }
        self.index_2_word = {
            0: 'hi'
        }

    def __getitem__(self, word: str) -> Any:
        return self.word_2_index[word]


test = Test()
test['hi']

0

In [ ]:
a = [1, 2, 3]
a[1:-1]