In [1]:
import numpy as np

# 矩阵 6 * 5
x = np.array([
    [1.00, 96.79, 2.00, 1.00, 2.00],
    [1.00, 110.39, 3.00, 1.00, 0.00],
    [1.00, 70.25, 1.00, 0.00, 2.00],
    [1.00, 99.96, 2.00, 1.00, 1.00],
    [1.00, 118.15, 3.00, 1.00, 0.00],
    [1.00, 115.08, 3.00, 1.00, 2.00]
])

# 列向量 6 * 1
y = np.array( [
    [287], [343], [199], [298], [340], [350],
])

In [2]:
x_t = x.T
A = np.dot(x_t, x)
A_inv = np.linalg.inv(A) # 求逆
B = np.dot(x_t, y)
w = np.dot(A_inv, B)
w

array([[124.55946459],
       [  0.31882858],
       [ 48.25692773],
       [ 37.22249353],
       [  1.89295003]])

In [9]:
x.T @ x

array([[6.00000000e+00, 6.10620000e+02, 1.40000000e+01, 5.00000000e+00,
        7.00000000e+00],
       [6.10620000e+02, 6.36841492e+04, 1.49461000e+03, 5.40370000e+02,
        6.64200000e+02],
       [1.40000000e+01, 1.49461000e+03, 3.60000000e+01, 1.30000000e+01,
        1.40000000e+01],
       [5.00000000e+00, 5.40370000e+02, 1.30000000e+01, 5.00000000e+00,
        5.00000000e+00],
       [7.00000000e+00, 6.64200000e+02, 1.40000000e+01, 5.00000000e+00,
        1.30000000e+01]])

In [10]:
cost = (y - np.dot(x, w)).T.dot(y - np.dot(x, w)) / ( 2 * x.shape[0])
cost

array([[8.23445195]])

In [11]:
test = [[1, 112, 3, 1, 0],
        [1, 110, 3, 1, 1]
        ]

np.dot(test, w)

array([[342.26154206],
       [343.51683493]])