In [3]:
import torch
import torch.nn as nn


class SimpleNetwork(nn.Module):
    def __init__(self, input_size, output_size):
        super(SimpleNetwork, self).__init__()
        self.linear = nn.Linear(input_size, output_size)

    def forward(self, x):
        return self.linear(x)


model = SimpleNetwork(3, 2)
model.linear.weight.shape

torch.Size([2, 3])

In [25]:
import torch
import torch.nn as nn

# 使用固定的随机种子
torch.manual_seed(0)

# 假设你有一个简单的线性模型
model = nn.Linear(10, 1)
print(model.weight)

input = torch.randn(1, 10)
output = model(input)  # 没有使用 torch.no_grad()
print(model.weight)

# 假设你有一个损失函数
loss = (output - torch.tensor([1.0])).pow(2).mean()

# 反向传播
loss.backward()

# 检查梯度
print('model.weight.grad', model.weight.grad)  # 如果没有使用 torch.no_grad()，会看到梯度

Parameter containing:
tensor([[-0.0024,  0.1696, -0.2603, -0.2327, -0.1218,  0.0848, -0.0063,  0.2507,
         -0.0281,  0.0837]], requires_grad=True)
Parameter containing:
tensor([[-0.0024,  0.1696, -0.2603, -0.2327, -0.1218,  0.0848, -0.0063,  0.2507,
         -0.0281,  0.0837]], requires_grad=True)
model.weight.grad tensor([[-0.4056, -1.7492, -1.1658, -1.5664,  0.0871, -1.6991, -2.0246,  0.0860,
          1.3963, -5.5364]])


In [16]:
import numpy as np
import torch
from torch.utils.data import DataLoader
from torchvision import datasets, transforms

a = np.array([
    [1, 2, 3],
    [4, 3, 1],
    [8, 3, 1]
])

a.argmax(axis=1, keepdims=True)
# 加载测试数据集
test_dataset = datasets.MNIST(
    root='./data', train=False, download=True, transform=transforms.ToTensor())
test_loader = DataLoader(
    dataset=test_dataset, batch_size=64, shuffle=False)

for images, labels in test_loader:
    print(images.shape)
    print(labels.shape)
    break

torch.Size([64, 1, 28, 28])
torch.Size([64])


In [19]:
import torch

# 创建两个不同形状的张量
a = torch.tensor([
    [1, 2, 3],
    [4, 3, 1],
    [8, 3, 1]
])
b = torch.tensor([
    2, 0, 2
])

torch.max(a, dim=1)

torch.return_types.max(
values=tensor([3, 4, 8]),
indices=tensor([2, 0, 0]))

In [21]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import precision_score
from sklearn.preprocessing import LabelBinarizer

# 假设有3个类别，y_true 是真实标签，y_pred 是模型的预测标签
y_true = [0, 1, 2, 0, 1, 2, 0, 2, 1, 1]
y_pred = [0, 2, 2, 0, 1, 0, 1, 2, 1, 1]

# 获取所有类别的精确率
precisions = precision_score(y_true, y_pred, average=None)
# 获取类别标签
classes = np.unique(y_true)

array([0.66666667, 0.75      , 0.66666667])