In [2]:
import torch
torch.randint(0, 2, (1, 10))

tensor([[1, 1, 0, 0, 1, 1, 0, 1, 0, 1]])

In [1]:
from transformers import BertTokenizer

tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
print(tokenizer.name_or_path)

In [ ]:
a = list([])
a[-1]

In [ ]:
import pandas as pd
df = pd.read_csv('dataset/level1/train.csv')
# 长度
len(df)

In [14]:
from transformers import BertTokenizer
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
print(tokenizer.tokenize('Hello,   world!'))
titles = 'Hello,   world!'
encoded = tokenizer(
    titles,
    padding=True,
    return_tensors='pt',
    max_length=512,
    truncation=True,
    return_token_type_ids=False,
)
encoded['attention_mask']

['hello', ',', 'world', '!']


tensor([[1, 1, 1, 1, 1, 1]])

In [19]:
import torch
a = torch.randint(0, 3, (1, 3))
b = torch.randint(0, 3, (1, 3))
c = torch.stack(
    [
        torch.cat([a[0], torch.zeros(3)],) for _ in range(3)
    ]
)

In [20]:
c

tensor([[0., 2., 0., 0., 0., 0.],
        [0., 2., 0., 0., 0., 0.],
        [0., 2., 0., 0., 0., 0.]])