In [ ]:
import nltk

nltk.download('punkt')

In [1]:
import pandas as pd

file_path = './data/Keyword Categorization.xlsx'
sheet_name = 'SG'

df = pd.read_excel(file_path, sheet_name=sheet_name)

Keyword             Category
0                           perromart  Pet Food & Supplies
1                     stojo singapore        Home & Living
2                               remax     Mobile & Gadgets
3                  seahorse singapore        Home & Living
4                  bluetooth earpiece     Mobile & Gadgets
...                               ...                  ...
24678                coklat singapore     Food & Beverages
24679                    wooden crate        Home & Living
24680  redmi 12 5g price in singapore     Mobile & Gadgets
24681                       nike pros    Sports & Outdoors
24682                           lg c2      Home Appliances

[24683 rows x 2 columns]

In [2]:
df.columns

Index(['Keyword', 'Category'], dtype='object')

In [3]:
from sklearn.feature_extraction.text import CountVectorizer

# 示例文档
documents = [
    'I love programming.',
    'Programming Programming is fun.',
    'Love is a beautiful feeling.'
]

# 创建 CountVectorizer 对象
vectorizer = CountVectorizer()

# 将文本数据转换为词频矩阵
X = vectorizer.fit_transform(documents)

# 输出词汇表（词到索引的映射）
print(vectorizer.vocabulary_)

# 输出稀疏矩阵
print(X.toarray())

{'love': 4, 'programming': 5, 'is': 3, 'fun': 2, 'beautiful': 0, 'feeling': 1}


[[0 0 0 0 1 1]
 [0 0 1 1 0 2]
 [1 1 0 1 1 0]]


In [14]:
import pandas as pd

data = pd.DataFrame({
    'text': ['黑糖姜 母茶']
})

data['text'].replace(r"[^\w\s]", "", regex=True)

0    黑糖姜 母茶
Name: text, dtype: object

In [20]:
import re

text = "黑糖姜母茶[/]"
matches = re.findall(r"[^\w\s]", text)
print(matches)

['[', '/', ']']


In [22]:
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

text = '黑糖姜母茶'
words = word_tokenize(text)
for word in words:
    print(word)
    # if word in stopwords.words('chinese'):
    #     print(word)

黑糖姜母茶


In [3]:
import pandas as pd

data = {'color': ['red', 'blue', 'green'],
        'size': ['small', 'medium', 'large']}
df = pd.DataFrame(data)

dummies = pd.get_dummies(df, columns=['color'])
print(dummies)

     size  color_blue  color_green  color_red
0   small       False        False       True
1  medium        True        False      False
2   large       False         True      False


In [4]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression

# 假设这是你的数据
data = {
    'feature_1': [1, 2, 3, 4],
    'feature_2': [5, 6, 7, 8],
    'feature_3': [9, 10, 11, 12],
    'target': ['class1', 'class2', 'class1', 'class3']
}

df = pd.DataFrame(data)

# 将 target 列设置为索引
df.set_index('target', inplace=True)

# 假设进行一个简单的文本分类任务，这里仅为示例
# 提取特征，假设 feature_1、feature_2、feature_3 为数值特征，这里进行简单处理
X = df[['feature_1', 'feature_2', 'feature_3']]
y = df.index

# 划分训练集和测试集
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42)

# 进行机器学习训练，这里使用逻辑回归作为示例
model = LogisticRegression()
model.fit(X_train, y_train)

# 进行预测等后续操作
predictions = model.predict(X_test)
print(predictions)

['class1']


In [3]:
import nltk
nltk.download('all')

[nltk_data] Downloading collection 'all'
[nltk_data]    | 
[nltk_data]    | Downloading package abc to
[nltk_data]    |     /Users/wuhonglei1/nltk_data...
[nltk_data]    |   Package abc is already up-to-date!
[nltk_data]    | Downloading package alpino to
[nltk_data]    |     /Users/wuhonglei1/nltk_data...
[nltk_data]    |   Unzipping corpora/alpino.zip.
[nltk_data]    | Downloading package averaged_perceptron_tagger to
[nltk_data]    |     /Users/wuhonglei1/nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger is already up-
[nltk_data]    |       to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger_eng to
[nltk_data]    |     /Users/wuhonglei1/nltk_data...
[nltk_data]    |   Unzipping
[nltk_data]    |       taggers/averaged_perceptron_tagger_eng.zip.
[nltk_data]    | Downloading package averaged_perceptron_tagger_ru to
[nltk_data]    |     /Users/wuhonglei1/nltk_data...
[nltk_data]    |   Unzipping
[nltk_data]    |       taggers/averaged_perceptron_ta

KeyboardInterrupt: 

In [1]:
import nltk
text = "This is a sample text."
tokens = nltk.word_tokenize(text)
print(tokens)

LookupError: 
**********************************************************************
  Resource punkt_tab not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('punkt_tab')
  
  For more information see: https://www.nltk.org/data.html

  Attempted to load tokenizers/punkt_tab/english/

  Searched in:
    - '/Users/wuhonglei1/nltk_data'
    - '/Users/wuhonglei1/Desktop/人工智能/python/dh_ai/myenv/nltk_data'
    - '/Users/wuhonglei1/Desktop/人工智能/python/dh_ai/myenv/share/nltk_data'
    - '/Users/wuhonglei1/Desktop/人工智能/python/dh_ai/myenv/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************


In [20]:
import spacy

nlp = spacy.load("en_core_web_sm")
doc = nlp("Apple is looking at buying U.K. startup for $1 billion")
for token in doc:
    print(token.text)

ModuleNotFoundError: No module named 'spacy'

In [9]:
import pandas as pd

df = pd.DataFrame({
    'text': ['I love programming.', 'Programming is fun.', 'Love is a beautiful feeling.']
})
df

text
0           I love programming.
1           Programming is fun.
2  Love is a beautiful feeling.

In [22]:
import nltk
print(nltk.data.path)

['/Users/wuhonglei1/nltk_data', '/Users/wuhonglei1/Desktop/人工智能/python/dh_ai/myenv/nltk_data', '/Users/wuhonglei1/Desktop/人工智能/python/dh_ai/myenv/share/nltk_data', '/Users/wuhonglei1/Desktop/人工智能/python/dh_ai/myenv/lib/nltk_data', '/usr/share/nltk_data', '/usr/local/share/nltk_data', '/usr/lib/nltk_data', '/usr/local/lib/nltk_data']


In [1]:
from sklearn.model_selection import train_test_split

train_data_list = [
    [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
]
y_list = [
    [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
    [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
]

for train_data, y in zip(train_data_list, y_list):
    X_train, X_test, y_train, y_test = train_test_split(
        train_data, y, test_size=0.2, random_state=42)

    print(X_train)
    print(X_test)
    print(y_train)
    print(y_test)

[6, 1, 8, 3, 10, 5, 4, 7]
[9, 2]
[0, 1, 0, 1, 0, 1, 0, 1]
[1, 0]
[16, 11, 18, 13, 20, 15, 14, 17]
[19, 12]
[0, 1, 0, 1, 0, 1, 0, 1]
[1, 0]
