In [3]:
import torch

torch.randint(1, 3, (1, 2))

tensor([[1, 2]])

In [7]:
import torch
a = torch.tensor([[
    [1, 2],
    [3, 4]
], [
    [5, 6],
    [7, 8]
]])
mask = torch.tensor([
    [True, False],
    [False, True]
])

a.masked_fill(mask, 0)

tensor([[[0, 2],
         [3, 0]],

        [[0, 6],
         [7, 0]]])

In [1]:
import torch

size = 5
torch.triu(torch.ones(size, size), diagonal=1).bool()

tensor([[False,  True,  True,  True,  True],
        [False, False,  True,  True,  True],
        [False, False, False,  True,  True],
        [False, False, False, False,  True],
        [False, False, False, False, False]])

In [ ]:
import torch

seq_len = 5
tgt_pad_mask = torch.tensor([0, 1, 1, 1, 0]).unsqueeze(
    0).unsqueeze(0).unsqueeze(0).bool()
tgt_sub_mask = torch.triu(torch.ones(
    (seq_len, seq_len), dtype=torch.bool), diagonal=1)
tgt_sub_mask

tensor([[ True, False, False, False, False],
        [ True,  True, False, False, False],
        [ True,  True,  True, False, False],
        [ True,  True,  True,  True, False],
        [ True,  True,  True,  True,  True]])

In [5]:
import torch
import torch.nn.functional as F

a = torch.tensor([
    [1, 2],
    [4, 4]
], dtype=torch.float32)
F.softmax(a)

/var/folders/4d/14nkpqsn4zs8c1dmkl0p4mxr0000gp/T/ipykernel_18191/3435619388.py:8: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  F.softmax(a)


tensor([[0.2689, 0.7311],
        [0.5000, 0.5000]])

In [6]:
import torch
from utils.model import create_subsequent_mask, create_pad_mask
pad_mask = create_pad_mask(torch.tensor([
    [1, 2, 0, 0],
    [3, 0, 0, 0]
]), pad_idx=0)
sub_mask = create_subsequent_mask(4)
print(pad_mask.shape, '\n', sub_mask.shape)
print((pad_mask & sub_mask).shape)

torch.Size([2, 1, 1, 4]) 
 torch.Size([4, 4])
torch.Size([2, 1, 4, 4])


In [7]:
pad_mask & sub_mask

tensor([[[[ True, False, False, False],
          [ True,  True, False, False],
          [ True,  True, False, False],
          [ True,  True, False, False]]],


        [[[ True, False, False, False],
          [ True, False, False, False],
          [ True, False, False, False],
          [ True, False, False, False]]]])

In [ ]:
import torch
a = torch.tensor([
    [1, 2],
    [3, 4]
])
a.reshape(1, 1, )

In [ ]:
len('的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的的')