In [3]:
a = list(['W', 'H', 'L'])
list(map(lambda s: s.lower(), a))

['w', 'h', 'l']

In [6]:
import torch
a = torch.tensor([
    [0, 3],
    [4, 0],
])
mask = a.eq(0)
a.masked_select(mask)

tensor([0, 0])

In [7]:
import torch

# 创建一个张量
tensor = torch.tensor([
    [1, 2, 3],
    [4, 5, 6]
])

# 创建掩码，选择大于 3 的元素
mask = tensor > 3

# 使用 masked_select
selected_elements = torch.masked_select(tensor, mask)

print("Original tensor:\n", tensor)
print("Mask:\n", mask)
print("Selected elements:", selected_elements)

Original tensor:
 tensor([[1, 2, 3],
        [4, 5, 6]])
Mask:
 tensor([[False, False, False],
        [ True,  True,  True]])
Selected elements: tensor([4, 5, 6])
