In [29]:
import torch

a = torch.tensor([-0.1, 0, 0.5, 1, 1.1])
a.clamp(0, 1)  # tensor([0.0, 0.5, 1.0, 1.0])

tensor([0.0000, 0.0000, 0.5000, 1.0000, 1.0000])

In [2]:
import torch
import torch.nn as nn

a = torch.tensor([
    [
        [
            [1, 2, 3],
            [4, 5, 6],
            [7, 8, 9]
        ]
    ]
], dtype=torch.float32)

up1 = nn.Upsample(scale_factor=1, mode='nearest')
up2 = nn.Upsample(scale_factor=2, mode='nearest')
up3 = nn.Upsample(scale_factor=3, mode='nearest')

up1(a), up2(a), up3(a)

(tensor([[[[1., 2., 3.],
           [4., 5., 6.],
           [7., 8., 9.]]]]),
 tensor([[[[1., 1., 2., 2., 3., 3.],
           [1., 1., 2., 2., 3., 3.],
           [4., 4., 5., 5., 6., 6.],
           [4., 4., 5., 5., 6., 6.],
           [7., 7., 8., 8., 9., 9.],
           [7., 7., 8., 8., 9., 9.]]]]),
 tensor([[[[1., 1., 1., 2., 2., 2., 3., 3., 3.],
           [1., 1., 1., 2., 2., 2., 3., 3., 3.],
           [1., 1., 1., 2., 2., 2., 3., 3., 3.],
           [4., 4., 4., 5., 5., 5., 6., 6., 6.],
           [4., 4., 4., 5., 5., 5., 6., 6., 6.],
           [4., 4., 4., 5., 5., 5., 6., 6., 6.],
           [7., 7., 7., 8., 8., 8., 9., 9., 9.],
           [7., 7., 7., 8., 8., 8., 9., 9., 9.],
           [7., 7., 7., 8., 8., 8., 9., 9., 9.]]]]))

In [9]:
from collections import namedtuple

Point = namedtuple('Point', ['x', 'y'])
Point(1, 2)

Point(x=1, y=2)

In [15]:
import torch

a = torch.tensor([
    [2, 3]
])

a.repeat(5)

RuntimeError: Number of dimensions of repeat dims can not be smaller than number of dimensions of tensor

In [16]:
[1] * 3

[1, 1, 1]