In [29]:
import torch

a = torch.tensor([-0.1, 0, 0.5, 1, 1.1])
a.clamp(0, 1)  # tensor([0.0, 0.5, 1.0, 1.0])

tensor([0.0000, 0.0000, 0.5000, 1.0000, 1.0000])

In [2]:
import torch
import torch.nn as nn

a = torch.tensor([
    [
        [
            [1, 2, 3],
            [4, 5, 6],
            [7, 8, 9]
        ]
    ]
], dtype=torch.float32)

up1 = nn.Upsample(scale_factor=1, mode='nearest')
up2 = nn.Upsample(scale_factor=2, mode='nearest')
up3 = nn.Upsample(scale_factor=3, mode='nearest')

up1(a), up2(a), up3(a)

(tensor([[[[1., 2., 3.],
           [4., 5., 6.],
           [7., 8., 9.]]]]),
 tensor([[[[1., 1., 2., 2., 3., 3.],
           [1., 1., 2., 2., 3., 3.],
           [4., 4., 5., 5., 6., 6.],
           [4., 4., 5., 5., 6., 6.],
           [7., 7., 8., 8., 9., 9.],
           [7., 7., 8., 8., 9., 9.]]]]),
 tensor([[[[1., 1., 1., 2., 2., 2., 3., 3., 3.],
           [1., 1., 1., 2., 2., 2., 3., 3., 3.],
           [1., 1., 1., 2., 2., 2., 3., 3., 3.],
           [4., 4., 4., 5., 5., 5., 6., 6., 6.],
           [4., 4., 4., 5., 5., 5., 6., 6., 6.],
           [4., 4., 4., 5., 5., 5., 6., 6., 6.],
           [7., 7., 7., 8., 8., 8., 9., 9., 9.],
           [7., 7., 7., 8., 8., 8., 9., 9., 9.],
           [7., 7., 7., 8., 8., 8., 9., 9., 9.]]]]))

In [9]:
from collections import namedtuple

Point = namedtuple('Point', ['x', 'y'])
Point(1, 2)

Point(x=1, y=2)

In [15]:
import torch

a = torch.tensor([
    [2, 3]
])

a.repeat(5)

RuntimeError: Number of dimensions of repeat dims can not be smaller than number of dimensions of tensor

In [3]:
import torch

a = torch.tensor([
    [1, 2],
    [3, 4]
], dtype=torch.float32)

a.mean(axis=0)

tensor([2., 3.])

In [17]:
import torch
import torch.nn as nn

a = torch.tensor([
    [1, 1]
], dtype=torch.float32)

b = torch.tensor([
    [1, 0]
], dtype=torch.float32)

nn.CosineSimilarity(dim=0)(a[0], b[0])

tensor(0.7071)

In [13]:
import torch
import torch.nn as nn
import torch.nn.functional as F


class ConvNet(nn.Module):
    def __init__(self):
        super(ConvNet, self).__init__()
        self.conv1 = nn.Conv2d(1, 6, 3)
        self.pool = nn.MaxPool2d(2, 2)
        self.conv2 = nn.Conv2d(6, 16, 3)
        self.fc1 = nn.Linear(16 * 6 * 6, 120)
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)
        self.fc4 = nn.Linear(10, 2)

        self.feature = nn.Sequential(
            self.conv1,
            self.pool,
            self.conv2,
            self.pool
        )

    def forward(self, x):
        x = self.pool(F.relu(self.conv1(x)))
        x = self.pool(F.relu(self.conv2(x)))
        x = x.view(-1, 16 * 6 * 6)
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x


model = ConvNet()
model, list(model.children())

(ConvNet(
   (conv1): Conv2d(1, 6, kernel_size=(3, 3), stride=(1, 1))
   (pool): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
   (conv2): Conv2d(6, 16, kernel_size=(3, 3), stride=(1, 1))
   (fc1): Linear(in_features=576, out_features=120, bias=True)
   (fc2): Linear(in_features=120, out_features=84, bias=True)
   (fc3): Linear(in_features=84, out_features=10, bias=True)
   (fc4): Linear(in_features=10, out_features=2, bias=True)
   (feature): Sequential(
     (0): Conv2d(1, 6, kernel_size=(3, 3), stride=(1, 1))
     (1): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
     (2): Conv2d(6, 16, kernel_size=(3, 3), stride=(1, 1))
     (3): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
   )
 ),
 [Conv2d(1, 6, kernel_size=(3, 3), stride=(1, 1)),
  MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False),
  Conv2d(6, 16, kernel_size=(3, 3), stride=(1, 1)),
  Linear(in_features=576, out_feat

In [5]:
'123' in ['123', '1234']

True

In [3]:
from PIL import Image
img_path = './data/content.png'
img = Image.open(img_path).convert('RGB')
img.width, img.height, img.size

(720, 479, (720, 479))

In [3]:
def test():
    return 1, tuple((2, 3))


a, b = test()
a, b

(1, (2, 3))

In [13]:
import torch

a = torch.tensor([1, 2])
type(a[0].item())

int

In [5]:
import numpy as np

a = np.array([
    [1, 2],
    [3, 4]
])

# 将矩阵 a 单位化处理
np.linalg.norm(a, axis=1, keepdims=True)

array([[2.23606798],
       [5.        ]])

In [ ]:
import torch
import torch.nn as nn


class MyModel(nn.Module):
    def __init__(self):
        super(MyModel, self).__init__()
        self.fc1 = nn.Linear(10, 20)
        self.fc2 = nn.Linear(20, 5)

    def forward(self, x):
        out = self.fc1(x)
        out = self.fc2(out)
        return out


model = MyModel()


def hook_fn(module, input, output):
    print(f"Hook called for module: {module}")
    print(f"Input shape: {tuple(input[0].shape)}")
    print(f"Output shape: {tuple(output.shape)}")


model.fc1.register_forward_hook(hook_fn)

input_tensor = torch.randn(32, 10)
output = model(input_tensor)

In [ ]:
import numpy as np

a = np.array([
    [1, 2],
    [3, 4]
])

a.mean(axis=0)

In [1]:
x = 2

x ** 3

8

In [10]:
import torch
import torch.nn as nn

a = torch.tensor([
    [1, 2, 3],
    [4, 5, 6]
])
a.contiguous()

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F


class MultiHeadSelfAttention(nn.Module):
    def __init__(self, d_model, num_heads, dropout=0.1):
        super(MultiHeadSelfAttention, self).__init__()
        assert d_model % num_heads == 0, "d_model 必须能被 num_heads 整除"
        self.num_heads = num_heads
        self.d_k = d_model // num_heads  # 每个头的维度

        # 定义线性层
        self.linear_q = nn.Linear(d_model, d_model)
        self.linear_k = nn.Linear(d_model, d_model)
        self.linear_v = nn.Linear(d_model, d_model)
        self.linear_out = nn.Linear(d_model, d_model)

        self.dropout = nn.Dropout(dropout)

    def forward(self, x, mask=None):
        batch_size, seq_length, d_model = x.size()

        # 线性变换并拆分成多头
        Q = self.linear_q(x).view(batch_size, seq_length,
                                  self.num_heads, self.d_k)
        K = self.linear_k(x).view(batch_size, seq_length,
                                  self.num_heads, self.d_k)
        V = self.linear_v(x).view(batch_size, seq_length,
                                  self.num_heads, self.d_k)

        # 调整维度以便计算注意力
        Q = Q.transpose(1, 2)  # [batch_size, num_heads, seq_length, d_k]
        K = K.transpose(1, 2)
        V = V.transpose(1, 2)

        # 计算注意力分数
        scores = torch.matmul(Q, K.transpose(-2, -1)) / (self.d_k ** 0.5)
        if mask is not None:
            scores = scores.masked_fill(mask == 0, float('-inf'))
        attention = F.softmax(scores, dim=-1)
        attention = self.dropout(attention)

        # 计算注意力输出
        # [batch_size, num_heads, seq_length, d_k]
        x = torch.matmul(attention, V)

        # 拼接多头并通过线性层
        x = x.transpose(1, 2).contiguous().view(
            batch_size, seq_length, d_model)
        x = self.linear_out(x)

        return x


# 示例使用
if __name__ == "__main__":
    batch_size = 2
    seq_length = 5
    d_model = 512
    num_heads = 8

    x = torch.randn(batch_size, seq_length, d_model)
    self_attn = MultiHeadSelfAttention(d_model, num_heads)
    output = self_attn(x)
    print(output.shape)  # 输出: torch.Size([2, 5, 512])

In [5]:
str = 'ฉันรักคุณ'
list(str)

['ฉ', 'ั', 'น', 'ร', 'ั', 'ก', 'ค', 'ุ', 'ณ']

In [6]:
list('ฉัน')

['ฉ', 'ั', 'น']